mysql:
  image: dockerizedrupal/mysql:2.0.0
  hostname: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - mysql-data
  environment:
    - TIMEZONE=Etc/UTC
    - GENERAL_LOG=Off
    - LOG_ERROR=Off
    - SLOW_QUERY_LOG=Off
    - LOG_QUERIES_NOT_USING_INDEXES=Off
    - LONG_QUERY_TIME=1
    - QUERY_CACHE_MIN_RES_UNIT=4K
    - MAX_ALLOWED_PACKET=16M
    - KEY_BUFFER_SIZE=16M
    - THREAD_CACHE_SIZE=8
    - INNODB_BUFFER_POOL_SIZE=128M
    - INNODB_FLUSH_LOG_AT_TRX_COMMIT=1
    - MAX_CONNECTIONS=151
mysql-data:
  image: dockerizedrupal/mysql:2.0.0
  hostname: mysql-data
  entrypoint: ["/bin/echo", "Data-only container for MySQL."]
  volumes:
    - /mysql
